Buildcloud (#342)
* Create action.yml

* Create docker_build_pr.yml

* Create docker_publish_release.yml

* Delete .github/workflows/.github/workflows/docker_publish_release.yml

* Create dockerhub_readme.yml

* Create docker_publish_release.yml

* Update docker_build_pr.yml

* Create buildtest

This is temporary file that test build cloud, and will be removed once the test is done.

* remove version buildx setup

Due to concurrency limit error
ERROR: failed to build: failed to solve: build cannot proceed concurrent build limit of 0 reached

* Configure builder with concurrency limits

* Use buildkitd-config

* Use buildkitd-config-inline

* Update action.yml

* Update action.yml

* Update action.yml

* Update action.yml

* Update docker_build_pr.yml

* Update action.yml

* Update action.yml

* Update action.yml

* Update action.yml

* Update action.yml

* Update action.yml

* Update action.yml

* Update action.yml

* Update action.yml

* Update docker_build_pr.yml

* add test on multi-platforms

* Create docker-test action.yml

* Fix verifying architecture

* Use macos-14 for arm64

* Add Install and Start Docker

* Fix docker start

* Use Colima

* Fix colima

* Fix colima

* Fix colima

* Fix colima

* Fix colima

* Use self-hosted arm64 runner for test

* Add permission

* Update docker_build_pr.yml

* Update docker_build_pr.yml

* Update docker_build_pr.yml

* Update docker_build_pr.yml

* Update docker_build_pr.yml

* Update docker_build_pr.yml

* Publish slack message

* comment out on push and pr

* Update docker_build_pr.yml

* Update docker_build_pr.yml

* Update slackapi

* Use icon

* Add comma

* remove icon url

* Use latest tag when push to main

* remove slack notification

* add slack publish on release

* fix co-pilot reviews